sudo: required
dist: trusty
language: node_js
node_js:
- 12.13.1
before_script:
- npm install -g surge
script:
- export DEPLOY_DOMAIN=https://preview-${TRAVIS_PULL_REQUEST}-ng-travis-antd.surge.sh
- surge teardown $DEPLOY_DOMAIN
- surge --project ./dist --domain $DEPLOY_DOMAIN
env:
  global:
  - secure: 1UjilCw4KCJlMUXi6gmUaOMxoJliF+Vy+WVZYDM5EjNsAbiLyGO+vTeabKkAP8X+SpkbPKWzXoKRmUjkK3UPG4+JGULwfpA013x5bKRDDtPFUY+PDLwbk4PT5qUc2Doc2AIQR2TtpFvGOIq0fGbviaPTqTwRQ1zmynGCVeLO/K8uBbxKVDUjGliAfFSwD6sagcLEHV1BY5AqbBptX3wXbif9a/mi7FrIu4HX3PBhzJyf4VRwZGEv8Gv6mlmIicNlvOP/CO+7dE69Tzbf5wPok44yY6p8s02Nik4LBR35Iay6C/GAjbx8PAiEa7ftSC4SyswVNpU+GtB/sC3R2IhCcfCDeG9JZcyJFOihb4bJ6rlqbjNnifycZA9huNQjwo0PHZU3Nnefy59+SVStXzI54KpI5M7g5HagS9IRakEGJoikkrnOMWJg6jPwJsFekeKuSzpUpJGtx70VUNkWmW2kYaQMYOlCLsuoqpxTSJ85j0hl77ijzdPVFHatPCjzs3h5cXImWEBmCS7C2zx1xFlnKdShNN8yuO/PCAnISe/dlwhM/YI0xgwTe84nJgcpFNxBK06h8OTfAbLT9R47FmZ9CO+P0VBIMtQXKmyTAdsQ2K/E0ta2totSWxcIZqRAALQmqdj/m10tEHCVuPBEEw3uIjMmXi5uNOOThZC3p2dE1RA=
  - secure: CEvitd5YlpqKl5ZzRL3UtvMoSXVF91B3BIs4551M6IW3RXrLnULoJqu9iKruZwXNN2iUwTbpi73Mivx7SqIwiUM9l0ctlEEOVFGAi+0XbkFBDpMFEM8OaSBX+JWedUD5NbfX90OMV9hcC53HusOqqF18F6YhoW/j0YQMdqquDBWwNcFge5XOgpFnxphLPvylNxGBLMFBfIID+vrjExK4GI5n5VGROcMxm19pASpeYz+mr/Z9qDR0lT4bARbj14DRYOCtb/HJnluEsrfAYbdS8o7LTcFg5z1ddjmZi+CcbfMRih5Aic8IngOAQlonOs/QoUmtTrdBb5FpzZjoVEOpAJ9XOFbZ5bZmt9axaIrS0E8EynF79Cs8L0KJ7e51y5DHLHZwMvtnlaunIuMqfMfrhfbgRS78LunITh4aXHF3QoRfsaqI2+5Iji+l/9om84eA5VCG86YVe0PH52dbX8RTMVq4O7P9duVCevvmnOg+QLJ8dBX01Rs6fWVM3aAsLSBn+LsaE8RBIuj0I/JeHpgJ3olEoS++1q0MTyeGRNR3GKnWCIbJclqCo84c0cxLEb+yRI32S7q+XfFozzpytfYqCU4HKf0s9t7X8NsgRrP/lqFusRnEnvwny4sQgZ/fukEoiV1NYtvdizGjXEgBi67WD194DmB7Y2wV5+L7NdqGJdI=
